### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by jeremiahrose** [jdegenstein/py-lib3mf#2]
It would be fantastic if this were also released as a Conda Forge package for those of us that use it!

**Comment by jdegenstein** [comment]
With the introduction of GH runners for MacOS-arm64 it looks like this is not as necessary anymore. I have released packages for cadquery-ocp 7.7.2 for MacOS-arm64 here: https://github.com/jdegenstein/ocp-build-system/releases/tag/7.7.2_macos_arm64

Ultimately the final missing piece of this puzzle is for these packages to be uploaded to PyPI, and I believe they are trying to solve that soon.

As far as releasing this package to conda, I am not planning to do this in the immediate future.
